export const LOGIN_STATE_PENDING = 'LOGIN_STATE_PENDING'
export const LOGIN_STATE_SUCCESS = 'LOGIN_STATE_SUCCESS'
export const LOGIN_STATE_FAILED = 'LOGIN_STATE_FAILED'
export const LOGOUT = 'LOGOUT'


