export const REMOVE_COORDS = "REMOVE_COORDS";
export const CHOOSE_COORDS = "CHOOSE_COORDS";
export const SAVE_ALL_ROUTES = "SAVE_ALL_ROUTES";
export const MAKE_NEW_OFFER = "MAKE_NEW_OFFER";
export const SAVE_CHOOSEN_COORDS_ROUTES = "SAVE_CHOOSEN_COORDS_ROUTES";
