language: node_js
node_js:
- stable
branches:
  only:
  - master
script:
- npm run check
deploy:
  provider: heroku
  app: test-jm-mihanizm56
  on:
    branch: develop
  api_key:
    secure: E9VQbKKccLN4aGy+kzF7qozvTbZFxSkMX5tg3JUUBRxo31oTATWYvl8jsqlMQI9rv7VPvAuV0OZMzoyHepl6E9sU6VnkO4jZ5WcYvcTJV3J56/yVYGvz8AenaHoNdACZP6mMOyiIAKQS5Aytb5enKpG2XJ2er9/BcJkOViMBTMm4zcj8VlGtGCJiPJdKWGsE7rDfOY2RUWPsiiPfscvRQh1taBKv/kvsaM0cnAHprIAqJfXj21nhWk5M04BeDP/Tz17LtJ09OZ198bVMVexgs2WT2pyTfn8zjhflbGHa14r/2Efb7RFq5ufCBRkTUBPA0jm1qQsssiYnjPYH9xKEozgEjXo1LRESzlCs6IUZydLtER6WFCqi9TKRV0idbPmTf5eSsN6NhPDFU0xzlvilZXZPleME/50BKcgb88eYasOWHGzgymL2Bbu0mxaujQ658aTJPDRxx0qPL/vY5iPDEdemlrEmq89P3twcYdcXZpa1aS7EZYpw/xBIpE1Ye5Hm9sCRxP3pezvyKhx9RnWwLW9qNOcQm2rjSB1ZNiqEcNi+zkdPwJwPJ867jxElfS4BZ9GawPSgjAja+o0TMPTvRhwwb1WEmBHUFwXpaKldYNfOqBuJ0aqOS28972xaE1S7eO/JT0yNfoMZNj/5LdcTfo49eMz099UYHral4enBGFY=
